import { TrendSource } from '@prisma/client';

export type MockTrendSeed = {
  externalId: string;
  source: TrendSource;
  authorHandle: string;
  authorFollowers: number;
  authorMedianViews: number;
  title: string;
  caption: string;
  hashtags: string[];
  durationSec: number;
  ageDays: number;
  views: number;
  likes: number;
  comments: number;
  shares: number;
  saves: number;
};

/**
 * Curated, not random. Deliberately spans small accounts with breakout
 * relative performance (rows 1, 4, 10, 19, 25, 27) and huge accounts posting
 * huge-but-unremarkable-for-them numbers (rows 6, 21) — a naive views-sorted
 * feed and a relative-performance-sorted feed must disagree on several of
 * these, or the scoring pipeline isn't actually being exercised.
 */
export const MOCK_TREND_SEED: MockTrendSeed[] = [
  {
    externalId: 'mock-001',
    source: 'TIKTOK',
    authorHandle: '@padel.mistakes',
    authorFollowers: 8_200,
    authorMedianViews: 14_000,
    title: '3 mistakes beginners make in padel',
    caption:
      "You're probably doing at least one of these. #3 is the one nobody talks about.",
    hashtags: ['padel', 'padeltips', 'beginner'],
    durationSec: 28,
    ageDays: 4,
    views: 612_000,
    likes: 54_000,
    comments: 1_800,
    shares: 9_200,
    saves: 21_000,
  },
  {
    externalId: 'mock-002',
    source: 'INSTAGRAM',
    authorHandle: '@tenniswithella',
    authorFollowers: 210_000,
    authorMedianViews: 90_000,
    title: 'Why your topspin forehand keeps floating out',
    caption:
      'One grip fix changed everything for me. Try it on your next rally.',
    hashtags: ['tennis', 'tennistips', 'forehand'],
    durationSec: 34,
    ageDays: 2,
    views: 340_000,
    likes: 22_000,
    comments: 640,
    shares: 3_100,
    saves: 8_700,
  },
  {
    externalId: 'mock-003',
    source: 'YOUTUBE',
    authorHandle: 'Padel Academy Pro',
    authorFollowers: 340_000,
    authorMedianViews: 60_000,
    title: "The 'W' positioning every padel doubles team should know",
    caption: 'Full breakdown with court diagrams and match footage.',
    hashtags: ['padel', 'doubles', 'positioning'],
    durationSec: 612,
    ageDays: 9,
    views: 210_000,
    likes: 9_800,
    comments: 540,
    shares: 1_200,
    saves: 4_300,
  },
  {
    externalId: 'mock-004',
    source: 'TIKTOK',
    authorHandle: '@courtcoach',
    authorFollowers: 4_100,
    authorMedianViews: 3_200,
    title: 'POV: your partner poaches every single lob',
    caption: 'We need to talk about court communication 😅',
    hashtags: ['padel', 'padelhumor', 'doubles'],
    durationSec: 19,
    ageDays: 1,
    views: 89_000,
    likes: 11_000,
    comments: 430,
    shares: 2_600,
    saves: 3_100,
  },
  {
    externalId: 'mock-005',
    source: 'INSTAGRAM',
    authorHandle: '@padel.femenino',
    authorFollowers: 56_000,
    authorMedianViews: 21_000,
    title: 'Girls padel warm-up routine before a tournament',
    caption: '10 minutes, no equipment, ready to compete.',
    hashtags: ['padel', 'warmup', 'womenspadel'],
    durationSec: 41,
    ageDays: 12,
    views: 48_000,
    likes: 3_900,
    comments: 180,
    shares: 410,
    saves: 2_200,
  },
  {
    externalId: 'mock-006',
    source: 'TIKTOK',
    authorHandle: '@megasportsclips',
    authorFollowers: 5_200_000,
    authorMedianViews: 5_800_000,
    title: 'Insane padel smash rally goes viral',
    caption: 'This point had the whole crowd on their feet.',
    hashtags: ['padel', 'sports', 'viral'],
    durationSec: 22,
    ageDays: 3,
    views: 6_100_000,
    likes: 410_000,
    comments: 3_200,
    shares: 28_000,
    saves: 19_000,
  },
  {
    externalId: 'mock-007',
    source: 'YOUTUBE',
    authorHandle: 'Fitness Reset',
    authorFollowers: 890_000,
    authorMedianViews: 140_000,
    title: 'A 5-minute mobility routine every racquet sport player needs',
    caption: 'Do this before you ever step on court again.',
    hashtags: ['fitness', 'mobility', 'racquetsports'],
    durationSec: 305,
    ageDays: 6,
    views: 410_000,
    likes: 18_000,
    comments: 720,
    shares: 3_300,
    saves: 22_000,
  },
  {
    externalId: 'mock-008',
    source: 'TIKTOK',
    authorHandle: '@gymhumor',
    authorFollowers: 1_200_000,
    authorMedianViews: 900_000,
    title: 'Types of people at the gym: padel edition',
    caption: 'Tag the friend who only trains for padel season 😂',
    hashtags: ['padel', 'gymhumor', 'relatable'],
    durationSec: 33,
    ageDays: 5,
    views: 2_100_000,
    likes: 260_000,
    comments: 5_400,
    shares: 41_000,
    saves: 8_900,
  },
  {
    externalId: 'mock-009',
    source: 'INSTAGRAM',
    authorHandle: '@business.playbook',
    authorFollowers: 320_000,
    authorMedianViews: 70_000,
    title: 'How boutique gyms are using scarcity to sell out classes',
    caption: 'The waitlist trick that tripled their conversion rate.',
    hashtags: ['smallbusiness', 'marketing', 'fitnessbiz'],
    durationSec: 52,
    ageDays: 18,
    views: 95_000,
    likes: 4_200,
    comments: 210,
    shares: 1_900,
    saves: 6_100,
  },
  {
    externalId: 'mock-010',
    source: 'TIKTOK',
    authorHandle: '@padel.tips.daily',
    authorFollowers: 62_000,
    authorMedianViews: 48_000,
    title: 'Stop doing THIS with your bandeja',
    caption: 'Fix your wrist angle and the shot fixes itself.',
    hashtags: ['padel', 'bandeja', 'padeltips'],
    durationSec: 26,
    ageDays: 2,
    views: 890_000,
    likes: 71_000,
    comments: 2_400,
    shares: 12_000,
    saves: 26_000,
  },
  {
    externalId: 'mock-011',
    source: 'YOUTUBE',
    authorHandle: 'Padel World Championships',
    authorFollowers: 1_100_000,
    authorMedianViews: 480_000,
    title: 'Match point highlights: World Padel Tour final',
    caption: 'Every winning point from the final set.',
    hashtags: ['padel', 'worldpadeltour', 'highlights'],
    durationSec: 480,
    ageDays: 21,
    views: 990_000,
    likes: 34_000,
    comments: 1_100,
    shares: 5_200,
    saves: 3_900,
  },
  {
    externalId: 'mock-012',
    source: 'INSTAGRAM',
    authorHandle: '@lifestyle.padel',
    authorFollowers: 41_000,
    authorMedianViews: 12_000,
    title: 'A day in the life running a padel club',
    caption: 'Court maintenance, member calls, and a lot of coffee.',
    hashtags: ['padel', 'dayinthelife', 'clublife'],
    durationSec: 88,
    ageDays: 30,
    views: 27_000,
    likes: 2_100,
    comments: 95,
    shares: 310,
    saves: 1_400,
  },
  {
    externalId: 'mock-013',
    source: 'TIKTOK',
    authorHandle: '@tennisexplained',
    authorFollowers: 89_000,
    authorMedianViews: 34_000,
    title: 'Beginner vs. intermediate vs. advanced serve toss',
    caption: 'Which one are you? Be honest.',
    hashtags: ['tennis', 'serve', 'levels'],
    durationSec: 37,
    ageDays: 15,
    views: 61_000,
    likes: 4_300,
    comments: 210,
    shares: 520,
    saves: 2_900,
  },
  {
    externalId: 'mock-014',
    source: 'TIKTOK',
    authorHandle: '@padel.dailydrills',
    authorFollowers: 15_000,
    authorMedianViews: 9_000,
    title: "The serve mistake that's costing you free points",
    caption: 'Small fix, immediate difference on your next match.',
    hashtags: ['padel', 'serve', 'padeldrills'],
    durationSec: 24,
    ageDays: 6,
    views: 210_000,
    likes: 19_000,
    comments: 780,
    shares: 4_100,
    saves: 8_200,
  },
  {
    externalId: 'mock-015',
    source: 'YOUTUBE',
    authorHandle: 'Business of Sport',
    authorFollowers: 210_000,
    authorMedianViews: 55_000,
    title: 'Why padel is the fastest growing sport in Europe',
    caption: 'The numbers behind the boom, and what it means for clubs.',
    hashtags: ['padel', 'sportsbusiness', 'growth'],
    durationSec: 540,
    ageDays: 40,
    views: 180_000,
    likes: 7_100,
    comments: 890,
    shares: 4_400,
    saves: 3_100,
  },
  {
    externalId: 'mock-016',
    source: 'INSTAGRAM',
    authorHandle: '@padel.humor',
    authorFollowers: 98_000,
    authorMedianViews: 61_000,
    title: "When your padel partner says 'yours' on everything",
    caption: 'We are not the same 🙃',
    hashtags: ['padel', 'padelhumor', 'relatable'],
    durationSec: 16,
    ageDays: 3,
    views: 340_000,
    likes: 41_000,
    comments: 1_900,
    shares: 8_700,
    saves: 4_200,
  },
  {
    externalId: 'mock-017',
    source: 'TIKTOK',
    authorHandle: '@strengthforsport',
    authorFollowers: 430_000,
    authorMedianViews: 130_000,
    title: '3 exercises to add power to your smash',
    caption: 'Rotational strength you can build in 15 minutes a week.',
    hashtags: ['fitness', 'padel', 'strength'],
    durationSec: 45,
    ageDays: 8,
    views: 260_000,
    likes: 15_000,
    comments: 640,
    shares: 3_900,
    saves: 17_000,
  },
  {
    externalId: 'mock-018',
    source: 'INSTAGRAM',
    authorHandle: '@padel.club.marketing',
    authorFollowers: 27_000,
    authorMedianViews: 8_000,
    title: 'The referral program that filled our beginner clinics',
    caption: 'One incentive, zero ad spend, fully booked in 3 weeks.',
    hashtags: ['padelclub', 'marketing', 'referrals'],
    durationSec: 63,
    ageDays: 22,
    views: 19_000,
    likes: 1_400,
    comments: 88,
    shares: 610,
    saves: 2_900,
  },
  {
    externalId: 'mock-019',
    source: 'TIKTOK',
    authorHandle: '@courtvision',
    authorFollowers: 3_100,
    authorMedianViews: 2_400,
    title: 'This positioning trick won us 4 straight points',
    caption: 'Small court adjustment, huge scoreboard difference.',
    hashtags: ['padel', 'strategy', 'padeltips'],
    durationSec: 21,
    ageDays: 1,
    views: 71_000,
    likes: 8_900,
    comments: 340,
    shares: 1_900,
    saves: 2_600,
  },
  {
    externalId: 'mock-020',
    source: 'YOUTUBE',
    authorHandle: 'Padel Explained',
    authorFollowers: 560_000,
    authorMedianViews: 190_000,
    title: 'Víbora vs. bandeja: when to use each shot',
    caption: 'Side-by-side slow motion comparison with commentary.',
    hashtags: ['padel', 'vibora', 'bandeja'],
    durationSec: 620,
    ageDays: 11,
    views: 310_000,
    likes: 14_000,
    comments: 980,
    shares: 2_600,
    saves: 12_000,
  },
  {
    externalId: 'mock-021',
    source: 'TIKTOK',
    authorHandle: '@sportscomedy',
    authorFollowers: 2_900_000,
    authorMedianViews: 2_100_000,
    title: 'Racquet sports as dating app profiles',
    caption: 'Padel players will feel personally attacked.',
    hashtags: ['comedy', 'sports', 'padel'],
    durationSec: 29,
    ageDays: 4,
    views: 3_400_000,
    likes: 380_000,
    comments: 6_100,
    shares: 52_000,
    saves: 9_800,
  },
  {
    externalId: 'mock-022',
    source: 'INSTAGRAM',
    authorHandle: '@padel.recruiting',
    authorFollowers: 19_000,
    authorMedianViews: 6_100,
    title: "Behind the scenes: building our club's first competitive team",
    caption: 'Tryouts, first practice, and the team photo.',
    hashtags: ['padelclub', 'team', 'behindthescenes'],
    durationSec: 74,
    ageDays: 25,
    views: 14_000,
    likes: 980,
    comments: 61,
    shares: 210,
    saves: 890,
  },
  {
    externalId: 'mock-023',
    source: 'TIKTOK',
    authorHandle: '@padel.nutrition',
    authorFollowers: 51_000,
    authorMedianViews: 22_000,
    title: 'What I eat before a padel tournament',
    caption: 'Full day of eating for a 3-match Saturday.',
    hashtags: ['padel', 'nutrition', 'athlete'],
    durationSec: 38,
    ageDays: 9,
    views: 89_000,
    likes: 6_700,
    comments: 290,
    shares: 1_100,
    saves: 5_900,
  },
  {
    externalId: 'mock-024',
    source: 'YOUTUBE',
    authorHandle: 'Racquet Lab',
    authorFollowers: 380_000,
    authorMedianViews: 95_000,
    title: "We tested 6 padel rackets so you don't have to",
    caption: 'Full comparison: control, power, and value for money.',
    hashtags: ['padel', 'racketreview', 'gear'],
    durationSec: 780,
    ageDays: 33,
    views: 220_000,
    likes: 9_400,
    comments: 610,
    shares: 1_800,
    saves: 8_100,
  },
  {
    externalId: 'mock-025',
    source: 'INSTAGRAM',
    authorHandle: '@padel.momtakes',
    authorFollowers: 8_900,
    authorMedianViews: 3_100,
    title: 'Trying padel for the first time at 45',
    caption: "I have never sweated this much having fun. I'm hooked.",
    hashtags: ['padel', 'over40', 'beginner'],
    durationSec: 55,
    ageDays: 5,
    views: 61_000,
    likes: 5_400,
    comments: 410,
    shares: 890,
    saves: 1_900,
  },
  {
    externalId: 'mock-026',
    source: 'TIKTOK',
    authorHandle: '@quickdrills',
    authorFollowers: 24_000,
    authorMedianViews: 15_000,
    title: 'A 60-second warm-up you can do courtside',
    caption: 'No space needed, no equipment, straight into the match.',
    hashtags: ['padel', 'warmup', 'quicktips'],
    durationSec: 24,
    ageDays: 14,
    views: 42_000,
    likes: 3_100,
    comments: 140,
    shares: 610,
    saves: 3_900,
  },
  {
    externalId: 'mock-027',
    source: 'INSTAGRAM',
    authorHandle: '@clubgrowth',
    authorFollowers: 12_000,
    authorMedianViews: 4_200,
    title: 'How we turned open house day into 30 new members',
    caption: 'The exact flow we ran, station by station.',
    hashtags: ['padelclub', 'membergrowth', 'openhouse'],
    durationSec: 67,
    ageDays: 28,
    views: 31_000,
    likes: 2_400,
    comments: 130,
    shares: 780,
    saves: 3_300,
  },
  {
    externalId: 'mock-028',
    source: 'TIKTOK',
    authorHandle: '@slowmoshots',
    authorFollowers: 670_000,
    authorMedianViews: 410_000,
    title: 'Slow motion smash from every angle',
    caption: 'Filmed at 240fps, the contact point says it all.',
    hashtags: ['padel', 'slowmotion', 'smash'],
    durationSec: 18,
    ageDays: 60,
    views: 520_000,
    likes: 38_000,
    comments: 890,
    shares: 4_100,
    saves: 6_200,
  },
  {
    externalId: 'mock-029',
    source: 'YOUTUBE',
    authorHandle: 'Padel Business Weekly',
    authorFollowers: 41_000,
    authorMedianViews: 9_000,
    title: 'Pricing strategy: peak vs. off-peak court rates explained',
    caption: 'The revenue math most clubs get wrong.',
    hashtags: ['padelclub', 'pricing', 'businessstrategy'],
    durationSec: 660,
    ageDays: 55,
    views: 8_100,
    likes: 410,
    comments: 61,
    shares: 190,
    saves: 890,
  },
  {
    externalId: 'mock-030',
    source: 'TIKTOK',
    authorHandle: '@padel.fails',
    authorFollowers: 340_000,
    authorMedianViews: 210_000,
    title: 'Padel fails that live in my head rent free',
    caption: 'The net-cord one at 0:14 is personal.',
    hashtags: ['padel', 'fails', 'funny'],
    durationSec: 31,
    ageDays: 48,
    views: 190_000,
    likes: 21_000,
    comments: 980,
    shares: 3_400,
    saves: 2_100,
  },
];
