// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Used by CLI commands (migrate, introspect, studio) — the app itself never
  // reads this, PrismaService builds its own adapter from DATABASE_URL
  // directly. Points at the DIRECT (non-pooled) connection because `migrate`
  // needs advisory locks / prepared statements a transaction-mode pooler
  // doesn't support.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
